[build]
publish = "dist"
command = "node --max-old-space-size=4096 ./node_modules/.bin/slidev build"

[build.environment]
NODE_VERSION = "24"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
